// Demo Data for El Salvador City Motorpool Heavy Equipment Maintenance System

const DEMO_SUPPLIERS = [
  {
    id: "SUP-001",
    name: "Monark Equipment Corporation",
    contactPerson: "Engr. Patrick Alcantara",
    phone: "+63 88 855-2241 / 0917-810-4491",
    email: "palcantara@monark-cat.com",
    address: "National Highway, Kauswagan, Cagayan de Oro City",
    specialty: "Official Caterpillar OEM Parts, Cat DEO Fluids, Hydraulic Seals & Filters"
  },
  {
    id: "SUP-002",
    name: "Civic Merchandising Inc.",
    contactPerson: "Dennis Villanueva",
    phone: "+63 88 858-3011 / 0918-922-1044",
    email: "sales.cdo@civicmdse.com.ph",
    address: "Tablon Highway, Cagayan de Oro City",
    specialty: "Volvo Construction Equipment, SDLG Wheel Loaders, Transmission & Powertrain Components"
  },
  {
    id: "SUP-003",
    name: "Topspot Heavy Equipment Inc.",
    contactPerson: "Rafael D. Tan",
    phone: "+63 88 856-7890 / 0920-951-3312",
    email: "rtan@topspot.com.ph",
    address: "Bulua Highway Junction, Cagayan de Oro City",
    specialty: "Heavy Machinery Undercarriage Parts, Excavator Tracks, Rollers, Sprockets & Buckets"
  },
  {
    id: "SUP-004",
    name: "El Salvador Auto & Heavy Parts Supply",
    contactPerson: "Grace Macas",
    phone: "+63 88 555-1204 / 0927-440-8911",
    email: "elsalvador.heavyparts@gmail.com",
    address: "Poblacion National Highway, El Salvador City, Misamis Oriental",
    specialty: "Local Quick-Turnaround Heavy Duty Oils, Batteries, Industrial Belts, Hardware & Bearings"
  },
  {
    id: "SUP-005",
    name: "Mindanao Hydraulic Hose & Seal Center",
    contactPerson: "Arthur Magno",
    phone: "+63 88 857-4419 / 0917-708-5522",
    email: "mindanaohydraulics@yahoo.com",
    address: "Cugman Industrial Area, Cagayan de Oro City",
    specialty: "High-Pressure Hydraulic Hoses, Flanges, O-Ring Seal Kits, Cylinder Rechroming"
  },
  {
    id: "SUP-006",
    name: "Powerbuilt Diesel Parts & Services",
    contactPerson: "Ariston Lim",
    phone: "+63 88 856-2299 / 0919-612-8800",
    email: "powerbuiltdiesel@gmail.com",
    address: "Gusa Highway, Cagayan de Oro City",
    specialty: "Diesel Injectors, Injection Pumps, Turbochargers, Starter Motors & Alternators"
  }
];

const DEMO_OPERATORS = [
  {
    id: "OP-001",
    name: "Danilo Ramos",
    certification: "TESDA NC II - Heavy Equipment Operation (Hydraulic Excavator)",
    licenseNumber: "HEO-EX-2021-0492",
    phone: "0917-432-8812",
    assignedUnit: "ESC-EQ-001",
    status: "Active",
    yearsExperience: 12
  },
  {
    id: "OP-002",
    name: "Eduardo Santos",
    certification: "TESDA NC II - Heavy Equipment Operation (Bulldozer / Earthmoving)",
    licenseNumber: "HEO-BD-2020-0118",
    phone: "0928-551-7734",
    assignedUnit: "ESC-EQ-002",
    status: "Active",
    yearsExperience: 15
  },
  {
    id: "OP-003",
    name: "Ramon Villanueva",
    certification: "TESDA NC II - Heavy Equipment Operation (Articulated Hauler / Rigid Dump)",
    licenseNumber: "HEO-HT-2019-0881",
    phone: "0919-603-4421",
    assignedUnit: "ESC-EQ-003",
    status: "Active",
    yearsExperience: 9
  },
  {
    id: "OP-004",
    name: "Vicente Gomez",
    certification: "TESDA NC II - Heavy Equipment Operation (Wheel Loader)",
    licenseNumber: "HEO-WL-2022-0314",
    phone: "0927-814-9905",
    assignedUnit: "ESC-EQ-004",
    status: "Active",
    yearsExperience: 8
  },
  {
    id: "OP-005",
    name: "Nestor Mendoza",
    certification: "TESDA NC III / DOLE Certified - Heavy Mobile Crane Specialist (120T)",
    licenseNumber: "DOLE-CR-2018-0042",
    phone: "0917-902-1133",
    assignedUnit: "ESC-EQ-005",
    status: "Active",
    yearsExperience: 18
  },
  {
    id: "OP-006",
    name: "Rolando Bautista",
    certification: "TESDA NC II - Heavy Equipment Operation (Motor Grader Road Profiling)",
    licenseNumber: "HEO-MG-2020-0722",
    phone: "0922-441-3389",
    assignedUnit: "ESC-EQ-006",
    status: "Active",
    yearsExperience: 14
  },
  {
    id: "OP-007",
    name: "Arnel Cruz",
    certification: "TESDA NC II - Heavy Equipment Operation (Compact Track Loader & Skid Steer)",
    licenseNumber: "HEO-CTL-2023-0105",
    phone: "0918-772-5501",
    assignedUnit: "ESC-EQ-007",
    status: "Active",
    yearsExperience: 6
  },
  {
    id: "OP-008",
    name: "Antonio Cañete",
    certification: "TESDA NC II - Multi-Equipment Operator (Backhoe Loader / Excavator Relief)",
    licenseNumber: "HEO-REL-2021-0941",
    phone: "0930-112-9988",
    assignedUnit: "Unassigned (Relief)",
    status: "Active",
    yearsExperience: 10
  }
];

const DEMO_FLEET = [
  {
    id: "ESC-EQ-001",
    name: "CAT 320 GC Hydraulic Excavator",
    type: "Excavator",
    make: "Caterpillar",
    model: "320 GC",
    serialNumber: "CAT0320GCD6721",
    year: 2021,
    currentHours: 2465,
    lastServiceHours: 2250,
    nextServiceHours: 2500,
    pmIntervalHours: 250,
    lastServiceDate: "2026-08-10",
    nextServiceDate: "2026-09-25",
    siteLocation: "Barangay Molugan Coastal Dike Project",
    assignedOperator: "Danilo Ramos",
    status: "Due Soon", // Operational, Due Soon, Overdue, In Shop, Grounded
    notes: "Assigned to flood control and river desilting operations. Heavy duty bucket and hydraulic thumb."
  },
  {
    id: "ESC-EQ-002",
    name: "Komatsu D65EX-18 Crawler Dozer",
    type: "Bulldozer",
    make: "Komatsu",
    model: "D65EX-18",
    serialNumber: "KOMD65EX98144",
    year: 2020,
    currentHours: 4135,
    lastServiceHours: 3850,
    nextServiceHours: 4100,
    pmIntervalHours: 250,
    lastServiceDate: "2026-05-14",
    nextServiceDate: "2026-09-01",
    siteLocation: "Barangay Cogon Farm-to-Market Road",
    assignedOperator: "Eduardo Santos",
    status: "Overdue",
    notes: "Earthmoving, land clearing, and sub-base leveling. Multi-shank ripper attached."
  },
  {
    id: "ESC-EQ-003",
    name: "Volvo A40G Articulated Haul Truck",
    type: "Haul Truck",
    make: "Volvo",
    model: "A40G",
    serialNumber: "VLV0A40G44219",
    year: 2019,
    currentHours: 6840,
    lastServiceHours: 6840,
    nextServiceHours: 7000,
    pmIntervalHours: 500,
    lastServiceDate: "2026-09-02",
    nextServiceDate: "2026-11-15",
    siteLocation: "El Salvador City Motorpool - Bay 2",
    assignedOperator: "Ramon Villanueva",
    status: "In Shop",
    notes: "Undergoing transmission output shaft seal replacement and brake disc check."
  },
  {
    id: "ESC-EQ-004",
    name: "John Deere 644X Wheel Loader",
    type: "Wheel Loader",
    make: "John Deere",
    model: "644X Hybrid",
    serialNumber: "JD644X883210",
    year: 2022,
    currentHours: 1985,
    lastServiceHours: 1750,
    nextServiceHours: 2000,
    pmIntervalHours: 250,
    lastServiceDate: "2026-07-22",
    nextServiceDate: "2026-09-20",
    siteLocation: "Poblacion Drainage & Material Transfer Station",
    assignedOperator: "Vicente Gomez",
    status: "Due Soon",
    notes: "Loading aggregates and asphalt mix for city road repairs. E-Drive transmission."
  },
  {
    id: "ESC-EQ-005",
    name: "Liebherr LTM 1120-4.1 Mobile Crane",
    type: "Mobile Crane",
    make: "Liebherr",
    model: "LTM 1120-4.1",
    serialNumber: "LBH1120CR7719",
    year: 2018,
    currentHours: 3250,
    lastServiceHours: 3000,
    nextServiceHours: 3500,
    pmIntervalHours: 500,
    lastServiceDate: "2026-06-30",
    nextServiceDate: "2026-12-15",
    siteLocation: "Barangay Taytay Multi-Purpose Gym Construction",
    assignedOperator: "Nestor Mendoza",
    status: "Operational",
    notes: "120-tonne all-terrain telescopic crane for heavy municipal structural erection. Annual safety certified."
  },
  {
    id: "ESC-EQ-006",
    name: "CAT 140M Motor Grader",
    type: "Motor Grader",
    make: "Caterpillar",
    model: "140M AWD",
    serialNumber: "CAT0140M99341",
    year: 2020,
    currentHours: 5120,
    lastServiceHours: 5000,
    nextServiceHours: 5250,
    pmIntervalHours: 250,
    lastServiceDate: "2026-08-01",
    nextServiceDate: "2026-10-15",
    siteLocation: "Barangay Amoros Access Road Concreting",
    assignedOperator: "Rolando Bautista",
    status: "Operational",
    notes: "Base-course road shaping and ditch maintenance. 14ft moldboard with carbide cutting edges."
  },
  {
    id: "ESC-EQ-007",
    name: "Bobcat T770 Compact Track Loader",
    type: "Compact Track Loader",
    make: "Bobcat",
    model: "T770",
    serialNumber: "BCT770TL55201",
    year: 2023,
    currentHours: 890,
    lastServiceHours: 750,
    nextServiceHours: 1000,
    pmIntervalHours: 250,
    lastServiceDate: "2026-08-18",
    nextServiceDate: "2026-11-01",
    siteLocation: "City Hall Compound Landscaping & Utility Works",
    assignedOperator: "Arnel Cruz",
    status: "Operational",
    notes: "Urban trenching, backfilling, and sweeper attachment operations. Heavy duty rubber tracks."
  }
];

const DEMO_LOGS = [
  {
    id: "WO-ESC-2026-015",
    equipmentId: "ESC-EQ-003",
    equipmentName: "Volvo A40G Articulated Hauler",
    date: "2026-09-02",
    meterHours: 6840,
    type: "Breakdown Repair", // PM Service, Breakdown Repair, Routine Inspection, Safety Certification
    priority: "Urgent", // Low, Medium, High, Urgent
    status: "In Progress", // Completed, In Progress, Scheduled, Waiting on Parts
    workSummary: "Transmission output shaft seal replacement and fluid leak repair.",
    workDetails: "Driver spotted transmission fluid pooling on underbelly plate during morning inspection. Drained fluid, disconnected driveshaft flange, and removed worn radial double-lip oil seal. Installed OEM Volvo oil seal kit and gasket. Refilled 28L transmission fluid. Ongoing leak test.",
    partsUsed: "1x Radial Seal (PN: 11102934), 28L Volvo WB102 Transmission Oil, Gasket Kit",
    supplier: "Civic Merchandising Inc.",
    repairCost: 88500.00,
    technician: "Mario De Leon (Master Mechanic)",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 7000,
    nextServiceDate: "2026-11-15"
  },
  {
    id: "WO-ESC-2026-014",
    equipmentId: "ESC-EQ-007",
    equipmentName: "Bobcat T770 Compact Track Loader",
    date: "2026-08-18",
    meterHours: 750,
    type: "PM Service",
    priority: "Medium",
    status: "Completed",
    workSummary: "750-Hour Scheduled Preventive Maintenance & Complete Filter Refresh.",
    workDetails: "Replaced 15W-40 heavy duty diesel engine oil and spin-on filter. Inspected hydrostatic drive fluid and case drain filter. Checked rubber track tension and adjusted grease tension cylinder. Cleaned air filtration assembly and greased all loader boom arm pins.",
    partsUsed: "15W-40 Synthetic Blend Diesel Oil (10L), Oil Filter 6678233, Fuel Filter 6667352, Air Filter 6698057",
    supplier: "El Salvador Auto & Heavy Parts Supply",
    repairCost: 35500.00,
    technician: "Benito Santos",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 1000,
    nextServiceDate: "2026-11-01"
  },
  {
    id: "WO-ESC-2026-013",
    equipmentId: "ESC-EQ-001",
    equipmentName: "CAT 320 GC Hydraulic Excavator",
    date: "2026-08-10",
    meterHours: 2250,
    type: "PM Service",
    priority: "Medium",
    status: "Completed",
    workSummary: "2,250-Hour PM Interval Service & Hydraulic System Inspection.",
    workDetails: "Full oil and filter replacement. Installed new engine oil filter and primary/secondary fuel filters. Collected fluid sample for laboratory analysis. Inspected boom and stick hydraulic cylinders for rod scoring or seal weeping (clean). Greased swing ring bearing.",
    partsUsed: "Cat DEO-ULS 15W-40 Oil (30L), Cat 1R-1808 Oil Filter, Cat 1R-0762 Fuel Filter, 5x Cartridges Cat Ultra Grease",
    supplier: "Monark Equipment Corporation",
    repairCost: 52000.00,
    technician: "Mario De Leon",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 2500,
    nextServiceDate: "2026-09-25"
  },
  {
    id: "WO-ESC-2026-012",
    equipmentId: "ESC-EQ-006",
    equipmentName: "CAT 140M Motor Grader",
    date: "2026-08-01",
    meterHours: 5000,
    type: "PM Service",
    priority: "High",
    status: "Completed",
    workSummary: "Major 5,000-Hour Powertrain & Hydraulic Overhaul Service.",
    workDetails: "Comprehensive 5,000-hour service overhaul. Replaced engine oil, transmission oil, left and right tandem drive oils, and circle drive gearbox lubricant. Replaced dual hydraulic return filters. Calibrated moldboard blade control joysticks and installed 4 new wear strips.",
    partsUsed: "Heavy Oils (120L total), Cat 1R-0777 Hydraulic Filters (x2), Transmission Filter, Moldboard Wear Strips",
    supplier: "Monark Equipment Corporation",
    repairCost: 176500.00,
    technician: "Engr. Patrick Alcantara",
    contractor: "Monark Equipment Field Service",
    nextServiceHours: 5250,
    nextServiceDate: "2026-10-15"
  },
  {
    id: "WO-ESC-2026-011",
    equipmentId: "ESC-EQ-004",
    equipmentName: "John Deere 644X Wheel Loader",
    date: "2026-07-22",
    meterHours: 1750,
    type: "PM Service",
    priority: "Low",
    status: "Completed",
    workSummary: "250-Hour Lube, Engine Oil & Safety Walkaround.",
    workDetails: "Drained crankcase oil, installed new oil filter, refilled with 15W-40 diesel oil. Tested auto-lube reservoir levels and purged axle grease lines. Checked tire pressures and rim wheel nut torque specifications.",
    partsUsed: "Plus-50 II Engine Oil (24L), RE509672 Filter, Heavy Duty EP Grease",
    supplier: "El Salvador Auto & Heavy Parts Supply",
    repairCost: 28500.00,
    technician: "Benito Santos",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 2000,
    nextServiceDate: "2026-09-20"
  },
  {
    id: "WO-ESC-2026-010",
    equipmentId: "ESC-EQ-005",
    equipmentName: "Liebherr LTM 1120-4.1 Mobile Crane",
    date: "2026-06-30",
    meterHours: 3000,
    type: "Safety Certification",
    priority: "High",
    status: "Completed",
    workSummary: "Annual Statutory Crane Structural Load Test & DOLE Safety Certification.",
    workDetails: "Certified non-destructive testing (NDT) magnetic particle testing performed on telescopic boom weldments, outrigger beams, and main hook block. Calibrated LICCON computer load moment limiter with test weights at rated capacities. Safety anti-two-block sensors verified. DOLE compliance certified.",
    partsUsed: "NDT Consumables, Replacement Wire Rope Cable Clips, Calibrated Test Weights",
    supplier: "Civic Merchandising Inc.",
    repairCost: 192000.00,
    technician: "Engr. Celso Morales (DOLE Accredited Inspector)",
    contractor: "Apex Lifting & Safety Inspection Phils",
    nextServiceHours: 3500,
    nextServiceDate: "2026-12-15"
  },
  {
    id: "WO-ESC-2026-009",
    equipmentId: "ESC-EQ-002",
    equipmentName: "Komatsu D65EX-18 Crawler Dozer",
    date: "2026-05-14",
    meterHours: 3850,
    type: "Breakdown Repair",
    priority: "Urgent",
    status: "Completed",
    workSummary: "Right Track Tensioner Seal Replacement & Track Re-alignment.",
    workDetails: "Dozer threw right crawler track while clearing quarry access road. Mobile motorpool service truck dispatched. Disassembled hydraulic track recoil cylinder, removed shredded piston seal. Installed heavy duty Komatsu seal repair kit and new track guide wear plates. Greased tensioner to 120mm sag spec.",
    partsUsed: "Komatsu Recoil Cylinder Seal Kit (PN: 14X-30-00120), Track Guide Wear Shoes (x2), EP Grease",
    supplier: "Topspot Heavy Equipment Inc.",
    repairCost: 148000.00,
    technician: "Mario De Leon",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 4100,
    nextServiceDate: "2026-09-01"
  },
  {
    id: "WO-ESC-2026-008",
    equipmentId: "ESC-EQ-001",
    equipmentName: "CAT 320 GC Hydraulic Excavator",
    date: "2026-04-18",
    meterHours: 2000,
    type: "PM Service",
    priority: "High",
    status: "Completed",
    workSummary: "2,000-Hour Major Hydraulic System Flush & Valve Recalibration.",
    workDetails: "Drained 190 liters of hydraulic fluid. Flushed system and refilled with Cat HYDO Advanced 10 fluid. Replaced pilot filter, return filter, and case drain filters. Recalibrated main hydraulic pump displacement angle and relief valve pressures.",
    partsUsed: "Cat HYDO Adv 10 (190L), Return Filter 1G-8878, Pilot Filter 093-7521, Breather Cap",
    supplier: "Monark Equipment Corporation",
    repairCost: 168000.00,
    technician: "Engr. Patrick Alcantara",
    contractor: "Monark Equipment Field Service",
    nextServiceHours: 2250,
    nextServiceDate: "2026-08-10"
  },
  {
    id: "WO-ESC-2026-007",
    equipmentId: "ESC-EQ-004",
    equipmentName: "John Deere 644X Wheel Loader",
    date: "2026-03-25",
    meterHours: 1500,
    type: "Routine Inspection",
    priority: "Low",
    status: "Completed",
    workSummary: "Quarterly Pre-Shift Brake & Safety System Walkaround Inspection.",
    workDetails: "Tested dual-circuit wet disc brakes stopping distances. Checked emergency steering secondary accumulator pressure. Tested backup camera, reverse alarm, and amber strobe beacon lights. Greased bucket linkage pins.",
    partsUsed: "Pin Greasing Cartridges, Wiper Blades",
    supplier: "El Salvador Auto & Heavy Parts Supply",
    repairCost: 14500.00,
    technician: "Benito Santos",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 1750,
    nextServiceDate: "2026-07-22"
  },
  {
    id: "WO-ESC-2026-006",
    equipmentId: "ESC-EQ-002",
    equipmentName: "Komatsu D65EX-18 Crawler Dozer",
    date: "2026-02-12",
    meterHours: 3600,
    type: "PM Service",
    priority: "Medium",
    status: "Completed",
    workSummary: "Routine 250-Hour Lube, Oil & Fuel Filter Replacement.",
    workDetails: "Replaced 15W-40 diesel engine oil and main lube filter. Replaced primary fuel filter/water separator. Cleaned air pre-cleaner bowl. Checked blade corner bit wear.",
    partsUsed: "Engine Oil (28L), Fuel Filter 600-319-3550, Oil Filter 600-211-1340",
    supplier: "Powerbuilt Diesel Parts & Services",
    repairCost: 36000.00,
    technician: "Mario De Leon",
    contractor: "El Salvador City Motorpool Shop",
    nextServiceHours: 3850,
    nextServiceDate: "2026-05-14"
  }
];

const EQUIPMENT_TYPES = [
  "Excavator",
  "Bulldozer",
  "Wheel Loader",
  "Haul Truck",
  "Mobile Crane",
  "Motor Grader",
  "Compact Track Loader",
  "Backhoe Loader",
  "Compactor / Roller",
  "Forklift / Telehandler",
  "Dump Truck",
  "Other"
];

const MAINTENANCE_TYPES = [
  "PM Service",
  "Breakdown Repair",
  "Routine Inspection",
  "Safety Certification",
  "Wear Part Replacement",
  "Fluid / Filter Change",
  "Electrical Overhaul"
];

const MAINTENANCE_STATUSES = [
  "Completed",
  "In Progress",
  "Scheduled",
  "Waiting on Parts"
];

const PRIORITIES = [
  "Low",
  "Medium",
  "High",
  "Urgent"
];
